### PR TITLE
build: Ignore unmodified files in SwiftLint script 🔨 

### PR DESCRIPTION
**Pull request by a7maad-ayman**
## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [x] 🔥 Performance Improvements
- [ ] ✅ Test
- [x] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Description
- Update SwiftLint script to exclude files that have no modifications.

## Related Tickets & Documents
...

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [x] 🙅 no documentation needed

## Screenshots

ct1
ct2

### CODE REVIEW

**Comment by ahmdmhasn** [comment]
Please rename the title to 

`build: Ignore unmodified files in SwiftLint script 🔨 `

**Review by ahmdmhasn — APPROVED** [review]

**Comment by ahmdmhasn** [comment]
@ a7maad-ayman Looks like you have a build error?

**Comment by a7maad-ayman** [comment]
> @ a7maad-ayman Looks like you have a build error?
@ahmdmhasn 
Screenshot 2023-06-03 at 11 39 15 PM

**Comment by ahmdmhasn** [comment]
> > @ a7maad-ayman Looks like you have a build error?
> > @ahmdmhasn
> 
> Screenshot 2023-06-03 at 11 39 15 PM

You had a build error running unit tests

**Comment by a7maad-ayman** [comment]
@ahmdmhasn 
i saw that in git-workflow, but i didn't change anything just the script

**Pull request merged**
